# Generated by Django 4.1.3 on 2023-06-19 15:23

from django.db import migrations, models
import django.db.models.deletion
import petHub.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='财务ID')),
                ('password', models.CharField(max_length=64, verbose_name='财务人员密码')),
                ('grade', models.CharField(choices=[('0', '总会计师'), ('1', '小组组长'), ('2', '组员')], default='2', max_length=1, verbose_name='财务职务等级')),
            ],
            options={
                'verbose_name': '财务',
                'verbose_name_plural': '财务',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='BlogID')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='Blog发布时间')),
                ('content', models.TextField(verbose_name='文字内容')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=petHub.models.rename_blog_picture, verbose_name='图片地址')),
                ('visible', models.BooleanField(default=True, verbose_name='对外显示')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('unit', models.CharField(default='个', max_length=32, verbose_name='价格单位')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('picture', models.ImageField(blank=True, default='static/parlour/None/com.png', null=True, upload_to=petHub.models.rename_commodity_picture, verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户名')),
                ('gender', models.CharField(choices=[('m', '男'), ('w', '女')], default='m', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='用户电话')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户地址')),
                ('password', models.CharField(max_length=64, verbose_name='用户登录密码')),
                ('bank_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='银行卡号')),
                ('pay_password', models.CharField(blank=True, max_length=6, null=True, verbose_name='用户支付密码')),
                ('head_picture', models.ImageField(blank=True, default='static/user/None/com_head.jpg', null=True, upload_to=petHub.models.rename_head_user, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='交易创建时间')),
                ('amount', models.IntegerField(default=1, verbose_name='交易数量')),
                ('state', models.BooleanField(default=False, verbose_name='订单完成状态')),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aid_transactions', to='petHub.accountant', verbose_name='财务ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cid_transactions', to='petHub.commodity', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uid_transactions', to='petHub.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
            },
        ),
        migrations.CreateModel(
            name='Parlour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='店铺ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='店铺名')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='店铺电话')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='店铺地址')),
                ('password', models.CharField(max_length=64, verbose_name='店铺密码')),
                ('head_picture', models.ImageField(blank=True, null=True, upload_to=petHub.models.rename_head_parlour, verbose_name='店铺头像')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_parlour', to='petHub.accountant', verbose_name='负责店铺的财务ID')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
        ),
        migrations.CreateModel(
            name='Interactives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=False, verbose_name='点赞')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='评论')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='交互创建时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_interactives', to='petHub.blog', verbose_name='BlogID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uid_interactives', to='petHub.user', verbose_name='与该Blog交互的用户')),
            ],
            options={
                'verbose_name': '用户交互',
                'verbose_name_plural': '用户交互',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='parlour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petHub.parlour', verbose_name='隶属店铺'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petHub.user', verbose_name='用户ID'),
        ),
    ]
